Assets/Scripts/FadeInOnApproach.cs
Assets/Scripts/PlayerMovement.cs

* fix bug where player respawns and gets stuck
* fix bug where the tutorial instructions' fade-in animations can be triggered and played multiple times

fix player respawn bug + tutorial fade-in bug

---

Assets/Prefabs/Credits/Credits.prefab
Assets/Scripts/UI/Credits.cs
Assets/Scripts/UI/Credits.cs.meta

* create new credits script to handle adjusting credits scroll speed based on keyboard and mouse inputs
* add credits script to credits prefab

implement using keyboard and mouse to speed up credits

---

Assets/Scenes/IRL Cutscenes/Drawing In Class.unity

Forgot to add the prefab to this level

Added Menu Holder to Drawing in Class

---

Assets/Animations/Characters/Stickman/Stickman Spawn 1.anim
Assets/Animations/Characters/Stickman/Stickman Spawn 2.anim
Assets/Animations/Characters/Stickman/Stickman.controller
Assets/Scripts/PlayerMovement.cs

- Added event in Spawn 1 animation that calls function in PlayerMovement, allowing player to only move once spawn animation has finished
- Not sure what happened in the controller but I'm sure its important

Fix Respawn movement bug

---

Assets/Prefabs/Background Pieces/Orange Object Instructions.prefab
Assets/Prefabs/Background Pieces/Orange Object Instructions.prefab.meta
Assets/Prefabs/Ground Pieces/Box Collider.prefab
Assets/Scenes/Levels/Mike Part 1.unity

- create new prefab for orange object instruction
- add it to Mike Pt 1
- hide level collider boxes

add fade-in instructions for orange objects

---

Assets/Prefabs/Drawing Canvas.prefab
Assets/Scripts/Drawing Canvas/DrawingCanvas.cs

- add audio source to Drawing Canvas's reset btn so sfx can play
- add logic to make audiosource stop playing sfx when not drawing

fix reset btn not working and looping drawing canvas sfx

---

Assets/Prefabs/Gameplay Systems/Cameras.prefab
Assets/Prefabs/Gameplay Systems/Dialogue System.prefab
Assets/Prefabs/UI/Level Selector.prefab
Assets/Prefabs/UI/Main Menu.prefab
Assets/Prefabs/UI/MenuHolder.prefab
Assets/Prefabs/UI/Pause Menu.prefab
Assets/Prefabs/UI/Settings Menu.prefab
Assets/Scripts/CameraScaler.cs
Assets/Scripts/CameraScaler.cs.meta
ProjectSettings/ProjectSettings.asset

- Enforce the main camera and UI to maintain 3:2 aspect ratio when screen size changes

fix game camera and UI scaling

---

Assets/Configuration/CursorConfig.asset
Assets/Scenes/IRL Cutscenes/Claire Cutoff.unity
Assets/Scenes/IRL Cutscenes/Claire Runs Into Nathan.unity
Assets/Scenes/IRL Cutscenes/Drawing In Class.unity
Assets/Scenes/UI/Credits.unity
Assets/Scenes/UI/Main Menu.unity
ProjectSettings/ProjectSettings.asset

- add cursor manager to IRL cutscenes and UI scenes
- remove cursor config from project settings 
- turns out that configuring it previously sets the cursor on the OS level, which conflicts with our cursor management
- update pencil cursor hotspot since we shrunk the cursor image

add cursor manager to IRL cutscenes and UI scenes

---

Assets/Scripts/Enemy/Enemy.cs

All enemies will initialize with a random frame now

Randomize Enemy Anim Frame

---

Assets/Prefabs/Ground Pieces/Claire Part 1 Ground.prefab
Assets/Prefabs/Ground Pieces/Claire Part 1 Ground.prefab.meta
Assets/Prefabs/Ground Pieces/Claire Part 2 Ground.prefab
Assets/Prefabs/Ground Pieces/Claire Part 2 Ground.prefab.meta
Assets/Scenes/Levels/Claire Part 1.unity
Assets/Scenes/Levels/Claire Part 2.unity

- redo claire levels with more polished version of the groundwork
- readjust drawing canvas, checkpoints, and focus areas in the scene
- cutscenes need some polish, planning to work with @rykwong to fix this

redo claire level with more polished version

---

Assets/Scenes/Levels/Tutorial.unity

Adjusted the amount of ink in Drawing Canvas 1 and Drawing Canvas 2 for the Tutorial Level

Changed Ink Amount in Drawing Canvases

---

Assets/Prefabs/UI/Level Selector Button Variant.prefab
Assets/Prefabs/UI/Level Selector Button Variant.prefab.meta
Assets/Prefabs/UI/Level Selector.prefab

- create prefab "Level Selector Button" which is a variant of "UI Button"
- add nathan levels to the level selector menu
- made the buttons smaller to fit everything in

add nathan levels to level selector

---

Assets/Scripts/LevelEndTrigger.cs

Added safe nav operator to LevelEndTrigger so that it'll work for IRL cutscenes.

Added safe nav op to Script

---

Assets/Scenes/Levels/Claire Part 1.unity

Updated the Maximum Ink Values for the 4 drawing canvases

Claire P1 Ink Amount Adjustments

---

Assets/Scenes/Levels/Claire Part 2.unity

Adjusted Ink Amount for Claire P2
(I realized now I accidentally moved where Stickman begins in the level and saved it, if this change in particular can be removed please let me know)

Claire P2 Ink Amount Adjustments

---

Assets/Prefabs/Drawing Canvas/Drawing Canvas.prefab
Assets/Prefabs/Gameplay Systems/Achievement Unlocker.prefab
Assets/Prefabs/Gameplay Systems/Game Manager.prefab
Assets/Prefabs/Orange Object.prefab
Assets/Scenes/Levels/Claire Part 1.unity
Assets/Scenes/Levels/Mike Part 1.unity
Assets/Scripts/Drawing Canvas/DrawingCanvas.cs
Assets/Scripts/LevelEndTrigger.cs
Assets/Scripts/OrangeObject.cs
Assets/Scripts/Steam/AchievementUnlocker.cs
Assets/Scripts/Steam/SteamManager.cs
Assets/Scripts/UI/Level Selector/LevelSelector.cs
Assets/Timelines/In-Game Cutscenes/Claire_Meets_Stickman.playable
Assets/Timelines/In-Game Cutscenes/Mike_Entrance.playable

- DrawingCanvas
- Add AchievementUnlocker script 
- Set it up to unlock the achievement when the player finishes drawing a line
- AchievementUnlocker
- Added Signal Receiver to prefab to receive signals from Cutscene Manager/Timeline
- Added enums for new achievements
- Add context menu item to make it easier to call SetAchievement from editor
- GameManager
- Added SteamManager script
- OrangeObject
- Add AchievementUnlocker script 
- Set it up to unlock the achievement when the player touches it
- Claire Part 1.unity, Mike Part 1.unity
- Update the scene with achievement integrations (some enemy position fixes too)
- LevelEndTrigger
- Add context menu item to make it easier to call LoadNextScene from editor
- SteamManager
- Add options to clear all stats and achievements on start (easier …

add 'Meet Claire', 'Meet Mike', 'Artist', and 'Touch!' steam achievements

---

Assets/Scenes/IRL Cutscenes/The End.unity
Assets/Scenes/IRL Cutscenes/The End.unity.meta
Assets/Timelines/IRL Cutscenes/The End.playable
Assets/Timelines/IRL Cutscenes/The End.playable.meta
ProjectSettings/EditorBuildSettings.asset

- create scene and timeline (cutscene) for "The End" final scene
- add to build settings

create 'the end' cutscene

---

Assets/Prefabs/Credits/Credits.prefab
Assets/Scenes/UI/Credits.unity
Assets/Timelines/Credits.playable

- add cameras prefab to credits scene (for audio listener and to get rid of play mode err)
- add polaroid images as decoration to credits
- update credits text
- remove photographs and sfx credits
- Add "!" after "thank you for playing"

update credits text + add credits decoration

---

Assets/Prefabs/Credits/Credits.prefab
Assets/Scenes/IRL Cutscenes/The End.unity
Assets/Scenes/UI/Credits.unity

- change "The End" timeline signal to be received by Cutscene Manager instead of Scene Loader (a singleton)
- add Level End Trigger to "The End" scene to perform the scene changing

fix issue where 'the end' scene cannot transition to 'main menu'

---

Assets/Scripts/Discord/DiscordController.cs

- add debug.logs and error handling to handle errors thrown by the discord instance
- change discord constructor's create flag to `NoRequireDiscord`
- fixes issue where unity closes and discord opens if the game starts with discord closed

add error handling to discord controller + fix discord opening bug

---

Assets/Scenes/Levels/Claire Part 2.unity
Assets/Scripts/Global.cs
Assets/Timelines/In-Game Cutscenes/Claire_Chair2.playable

- add achievement unlocker obj and signal emitter to trigger the "Draw a Chair" achievement in Claire Part 2

add chair achievement

---

Assets/Scripts/ActivateTrigger.cs
Assets/Scripts/Audio/BGMEnqueuer.cs
Assets/Scripts/Checkpoint.cs
Assets/Scripts/CutsceneTrigger.cs
Assets/Scripts/Dialogue/DialogueAudio.cs
Assets/Scripts/Discord/DiscordController.cs
Assets/Scripts/Drawing Canvas/DrawingArea.cs
Assets/Scripts/Drawing Canvas/DrawingCanvas.cs
Assets/Scripts/Enemy/WallPoint.cs
Assets/Scripts/OrangeObjectTrigger.cs
Assets/Scripts/PlayerMovement.cs
Assets/Scripts/Saving and Loading/GameManager.cs
Assets/Scripts/Saving and Loading/ObjectSerializer.cs
Assets/Scripts/Saving and Loading/PersistentStoreManager.cs
Assets/Scripts/Saving and Loading/Serializable Data Objects/CheckpointData.cs
Assets/Scripts/Saving and Loading/Serializable Data Objects/CutsceneData.cs
Assets/Scripts/Steam/AchievementUnlocker.cs
Assets/Scripts/Steam/SteamManager.cs
Assets/Scripts/UI/Level Selector/LevelSelector.cs
Assets/Scripts/UI/MainMenu.cs
Assets/Scripts/UI/MenuManager.cs

- Enable logger only in non-production (debug) builds
- Update log messages to include the related object/class/script file

debug.log only in debug build + improve debug.logs

---

Assets/Scenes/UI/Main Menu.unity
Assets/Scripts/Audio/AudioSystem.cs

- reset the AudioSystem prefab overrides in MainMenu that cause BGM not to loop
- remove outdated SFX stuff from AudioSystem

fix non-looping bgm + remove sfx stuff from audio system

---

Assets/Scenes/Levels/Chase.unity

Changed the maximum ink amounts for the puzzles in the Chase Level

Changed Ink Amounts

---

Assets/Prefabs/UI/UI Dropdown.prefab
Assets/Scripts/Steam/SteamManager.cs
Assets/Scripts/UI/Settings Menu/AudioSettings.cs
Assets/Scripts/UI/Settings Menu/DisplaySettings.cs

- UI Dropdown.prefab
- update scroll sensitivity so scroll wheel can scroll faster
- SteamManager.cs
- only restart the game and relaunch with Steam for production build (easier to debug and run test builds)
- AudioSettings.cs
- update debug.log prefix
- DisplaySettings.cs
- update debug.log prefix
- fix the bug that essentially made the display settings ineffective
- entering fullscreen would immediatelyrevert back to windowed mode (logic bug)

fix issues with display settings not working

---

Assets/Scenes/Levels/Claire Part 2.unity
Assets/Scripts/Drawing Canvas/DrawingCanvas.cs
Assets/Timelines/In-Game Cutscenes/Claire Part 2/1 Claire Chair 1.playable

- show a UI button instead of using the drawing canvas as a trigger
- this gives the player more time/clicks to draw the chair

show 'done' button for chair cutscene

---

Assets/Animations/Characters/Mike/StickMan Trapped.anim
Assets/Prefabs/Drawing Canvas/Drawing Canvas.prefab
Assets/Scenes/Levels/Chase.unity
Assets/Scenes/Levels/Claire Part 1.unity
Assets/Scenes/Levels/Claire Part 2.unity
Assets/Scenes/Levels/Mike Part 1.unity
Assets/Scenes/Levels/Mike Part 2.unity
Assets/Scenes/Levels/Mike Part 3 (Death).unity
Assets/Scenes/Levels/Nathan Part 1.unity
Assets/Scenes/Levels/Nathan Part 2.unity
Assets/Scenes/Levels/Nathan Part 3.unity
Assets/Scenes/Levels/Tutorial.unity
Assets/Scripts/Drawing Canvas/ResetButton.cs
Assets/Timelines/In-Game Cutscenes/Claire Part 2/C2 1.1 Claire Chair.playable
Assets/Timelines/In-Game Cutscenes/Mike Part 3/Mike_Death.playable

fix more cutscene issues reported by avery

---

Assets/Prefabs/Drawing Canvas/Drawing Area.prefab
Assets/Prefabs/Drawing Canvas/Drawing Canvas.prefab
Assets/Prefabs/Drawn Lines/Black Line.prefab
Assets/Prefabs/Drawn Lines/Blue Line.prefab
Assets/Prefabs/Drawn Lines/Line.prefab
Assets/Scripts/Drawing Canvas/DrawingCanvas.cs
Assets/Scripts/Drawing Canvas/ResetButton.cs
Assets/Timelines/In-Game Cutscenes/Claire Part 2/C2 5 Claire Cliff.playable

- fix z-value of drawing canvas, area, reset btn and lines
- also tweak drawing canvas math

fix issue where player cannot draw over line in canvas

---

Assets/Scenes/Levels/Mike Part 1.unity
Assets/Scenes/Levels/Mike Part 2.unity

Adjusted the maximum ink amounts for the drawing Canvases of Mike Part 1 and Mike Part 2

Added Ink Amount Adjustments

---

Assets/Scenes/Levels/Claire Part 1.unity
Assets/Scenes/Levels/Claire Part 2.unity
Assets/Timelines/Level Cutscenes/Claire Part 1/C1 4 Claire Cliff.playable
Assets/Timelines/Level Cutscenes/Claire Part 2/C2 5 Claire Cliff.playable

- added a box collider to both claire 1 and 2's cliff cutscenes
- this prevents stickman from falling down the cliff after claire pulls stickman up and softlocking the game

activate box collider after claire cliff cutscenes to prevent softlocking game

---

Assets/Scripts/Audio/AudioSystem.cs
Assets/Scripts/Drawing Canvas/DrawingArea.cs
Assets/Scripts/PlayerMovement.cs
Assets/Scripts/Saving and Loading/Serializable Data Objects/PlayerData.cs

- track and save the last position of stickman before it triggers a cutscene
- that way, we can reposition stickman on the trigger when loading
- replay the bgm if same track is enqueued but with different pitch
- fix issue where the cursor gets stuck as a pencil even though the mouse isn't inside a drawing area

fix some script-related bugs

---

Assets/Prefabs/Ground Pieces/Claire Part 1 Ground.prefab
Assets/Prefabs/Ground Pieces/Claire Part 2 Ground.prefab
Assets/Prefabs/Ground Pieces/Mike Part 1 Ground.prefab
Assets/Prefabs/Ground Pieces/Mike Part 2 Ground.prefab

Adjusted the Scale and Opacity for the new background level drawings in the Claire and Mike Levels (Both parts)

Adjusted Scale and Opacity

---

Assets/Dialogue/2 Cutscene Claire/2.asset

Changed the wording of a few pieces of dialogue for better flow/in character storytelling

Adjusted a few dialogue objects

---

Assets/Animations/Characters/Mike/Mike Part 2/2.1 Mike Run to Edge.anim
Assets/Animations/Characters/Mike/Mike Part 2/2.1 Mike Run to Edge.anim.meta
Assets/Animations/Characters/Mike/Mike Part 2/2.2 Mike Run Away from Edge.anim
Assets/Animations/Characters/Mike/Mike Part 2/2.2 Mike Run Away from Edge.anim.meta
Assets/Animations/Characters/Mike/Mike Part 2/3.1 Mike Takes Down Row of Scribbles.anim
Assets/Animations/Characters/Mike/Mike Part 2/3.1 Mike Takes Down Row of Scribbles.anim.meta
Assets/Animations/Characters/Mike/Mike Part 2/3.2 Mike Jumps Down.anim
Assets/Animations/Characters/Mike/Mike Part 2/3.2 Mike Jumps Down.anim.meta
Assets/Animations/Characters/Mike/Mike Part 2/3.3 Mike Hops Away.anim
Assets/Animations/Characters/Mike/Mike Part 2/3.3 Mike Hops Away.anim.meta
Assets/Animations/Enemies/Enemy.controller
Assets/Animations/Enemies/Pit Enemy 3x.controller
Assets/Animations/Enemies/Scribble Wall.controller
Assets/Prefabs/Ground Pieces/Mike Part 2 Ground.prefab
Assets/Scenes/Levels/Mike Part 2.unity
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 2.1 Stickman Falls Down Hole.playable
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 2.1 Stickman Falls Down Hole.playable.meta
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 2.2 Stickman Falls Down Hole.playable
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 2.2 Stickman Falls Down Hole.playable.meta
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 3 Mike Meets Up with Stickman Again.playable
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 3 Mike Meets Up with Stickman Again.playable.meta
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 5 Drop Bridge.playable
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 5 Drop Bridge.playable.meta

- add backlogged mike part 2 cutscenes
- 2 stickman falls down hole
- 3 mike meets up with stickman
- 5 drops bridge

Add backlog mike 2 cutscenes

---

Assets/Audio/Music/Chase.wav.meta
Assets/Audio/Music/Nathan 1.wav.meta
Assets/Audio/Music/Nathan 2.wav.meta
Assets/Audio/Music/Nathan 3.wav.meta
Assets/Scenes/Levels/Chase.unity
Assets/Scenes/Levels/Nathan Part 1.unity
Assets/Scenes/Levels/Nathan Part 2.unity
Assets/Scenes/Levels/Nathan Part 3.unity

- add new BGM tracks
- add BGMEnqueuer to chase and nathan levels

add and enqueue chase and nathan levels bgm

---

Assets/Prefabs/Ground Pieces/Mike Part 1 Ground.prefab
Assets/Prefabs/Ground Pieces/Mike Part 2 Ground.prefab
Assets/Scenes/Levels/Mike Part 1.unity
Assets/Scenes/Levels/Mike Part 2.unity
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 3.2 Mike Fall.playable
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 4.3 Mike Gets Up.playable
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 4 Mike Holds Scribbles.playable

- resolve these mike level bugs
- ![image](https://github.com/jalenng/Draw/assets/42555186/1ac6b621-cdab-4e73-ab32-244ec284a24c)
- ![image](https://github.com/jalenng/Draw/assets/42555186/866d54b9-64f4-4c6b-8879-556cae0afd01)
- ![image](https://github.com/jalenng/Draw/assets/42555186/203e4240-d8b0-4e56-9e25-e25747f372bb)
- ![image](https://github.com/jalenng/Draw/assets/42555186/0293f9f2-d9e8-4936-a3bc-7b63465ea6de)

fix reported mike part 1 and 2 bugs

---

Assets/Prefabs/Ground Pieces/Nathan Part 2 Ground.prefab
Assets/Scenes/Levels/Nathan Part 2.unity
Assets/Scenes/Levels/Nathan Part 3.unity

Finally ported over the Ambient Sound Players and placed them in N2 and N3. Also, added some colliders for tables in N2.

Added Ambient Sound to N2 + N3

---

Assets/Prefabs/Ground Pieces/Mike Part 2 Ground.prefab
Assets/Scenes/Levels/Mike Part 1.unity
Assets/Scenes/Levels/Mike Part 2.unity
Assets/Scripts/Camera Blending/FocusArea.cs
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 4.2 Mike Gets Saved.playable

- fix issue where after the Mike Gets Saved cutscene finishes, the focus area remains stuck
- adjust mike part 2 ramp slot widths so the orange object pieces fit

fix more mike level issues

---

Assets/Scenes/IRL Cutscenes/Claire Cutoff.unity
Assets/Scenes/IRL Cutscenes/Claire Runs Into Nathan.unity
Assets/Scenes/IRL Cutscenes/Mike Cutoff.unity
Assets/Scenes/Levels/Mike Part 3.unity
Assets/Scripts/Audio/AudioSystem.cs
Assets/Scripts/Audio/BGMEnqueuer.cs
Assets/Scripts/Discord/DiscordController.cs

- add a function in AudioSystem to stop BGM
- update BGMEnqueuer to support null AudioClip (which will enqueue silence)
- add silent BGMEnqueuer to Mike Part 3 (death)
- add BGMEnqueuer to IRL cutscenes
- update DiscordController to prevent spamming logs when discord is not open

add BGMEnqueuer to IRL cutscenes

---

Assets/Prefabs/Ground Pieces/Claire Part 1 Ground.prefab
Assets/Prefabs/Ground Pieces/Claire Part 2 Ground.prefab
Assets/Prefabs/Ground Pieces/Mike Part 1 Ground.prefab
Assets/Prefabs/Ground Pieces/Mike Part 2 Ground.prefab

Found the opacity of the background pieces to be too transparent, readjusted them individually accordingly

Readjusted opacity

---

Assets/Scenes/IRL Cutscenes/Claire Cutoff.unity
Assets/Scenes/IRL Cutscenes/Claire Runs Into Nathan.unity
Assets/Scenes/IRL Cutscenes/Drawing In Class.unity
Assets/Scenes/IRL Cutscenes/Mike Cutoff.unity

set the BGM Enqueuers in the IRL cutscenes to None so the BGM music stops

stop bgm for irl cutscenes

---

Assets/Scenes/IRL Cutscenes/The End.unity
Assets/Scenes/Levels/Chase.unity
Assets/Scenes/Levels/Nathan Part 3.unity
Assets/Scenes/UI/Credits.unity
Assets/Scripts/Global.cs
Assets/Timelines/Credits.playable
Assets/Timelines/IRL Cutscenes/The End.playable
Assets/Timelines/Level Cutscenes/Nathan Part 3/N3 19 Confronting Nathan.playable

- move "Finish The Game" achievement from end of credits to end of "The End" scene
- create "Meet Nathan" achievement which is unlocked after last level cutscene

move 'the end' and add 'meet nathan' achievement

---

Assets/Prefabs/Gameplay Systems/Dialogue System.prefab
Assets/Prefabs/UI/Content Warning.prefab
Assets/Prefabs/UI/Dialog.prefab
Assets/Scenes/IRL Cutscenes/Claire Cutoff.unity
Assets/Scenes/IRL Cutscenes/Claire Runs Into Nathan.unity
Assets/Scenes/IRL Cutscenes/Drawing In Class.unity
Assets/Scenes/IRL Cutscenes/Mike Cutoff.unity
Assets/Scenes/IRL Cutscenes/The End.unity
Assets/Scripts/Dialogue/DialogueSystem.cs
Assets/Scripts/UI/Components/CanvasGroupVisibility.cs
Assets/Scripts/UI/Components/CanvasGroupVisibility.cs.meta
Assets/Scripts/UI/MainMenu.cs

* fix regression issue where after clicking a dialog button, pressing space will activate the selected button
* caused by show/hide dialog refactoring for the content warning dialog
* fixed and now using canvas group to show/hide and enable/disable interaction

fix issue where dialogs are keyboard-interactable even when hidden

---

Assets/Animations/Levels/Stickman/Stickman Spawn.anim
Assets/Animations/Levels/Tutorial.meta
Assets/Animations/Levels/Tutorial/Stickman Chase Intro.anim
Assets/Animations/Levels/Tutorial/Stickman Chase Intro.anim.meta
Assets/Prefabs/UI/Content Warning.prefab
Assets/Scenes/Levels/Tutorial.unity
Assets/Timelines/Level Cutscenes/Tutorial.meta
Assets/Timelines/Level Cutscenes/Tutorial/T1 Stickman Spawn Intro.playable
Assets/Timelines/Level Cutscenes/Tutorial/T1 Stickman Spawn Intro.playable.meta

- i previously broke the stickman spawn animation while cleaning up the animation controller
- used the cutscene method to reimplement the stickman spawn animation (similar to chase level intro)
- also did a quick change to the content warning dialog message

fix broken stickman spawn animation in tutorial

---

Assets/Animations/Levels/Stickman/Stickman Idle Startled.controller
Assets/Animations/Levels/Stickman/Stickman Idle Startled.controller.meta
Assets/Dialogue/Claire Part 1/0 Meeting Claire.asset
Assets/Scenes/Levels/Chase.unity
Assets/Scenes/Levels/Claire Part 2.unity
Assets/Scenes/Levels/Mike Part 1.unity
Assets/Scripts/PlayerMovement.cs
Assets/Timelines/Level Cutscenes/Claire Part 2/C2 1.1 Claire Chair.playable
Assets/Timelines/Level Cutscenes/Claire Part 2/C2 1.2 Claire Chair.playable
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 2.2 Mike Tackle Scribble.playable
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 4.1 Mike Fight Scribble.playable

- fixed more bugs reported by avery
- replaced orange objects in chase level with correct sprite
- polish cutscene group positioning 
- fix certain scenes where a character is stuck on a sprite frame instead of going through the idle animation

fixed more bugs reported by avery

---

Assets/Animations/Scene Transition/Fade Out.anim
Assets/Prefabs/Gameplay Systems/Scene Loader.prefab
Assets/Prefabs/UI/Level Selector.prefab
Assets/Prefabs/UI/Menu Manager.prefab
Assets/Prefabs/UI/Pause Menu.prefab
Assets/Prefabs/UI/Settings Menu.prefab
Assets/Prefabs/UI/UI Slider.prefab
Assets/Scripts/Drawing Canvas/DrawingArea.cs
Assets/Scripts/Drawing Canvas/ResetButton.cs
Assets/Scripts/UI/Components/CanvasGroupVisibility.cs
Assets/Scripts/UI/Level Selector/LevelSelector.cs
Assets/Scripts/UI/MenuManager.cs
Assets/Scripts/UI/PauseMenu.cs
Assets/Scripts/UI/Settings Menu/SettingsMenu.cs

- move away from enabling/disabling the canvas component
- it was causing UI elements to jump when the layout group component activates and repositions the elements
- instead, use canvas groups and the CanvasGroupVisibility script
- make DrawingArea code detecting whether game is paused a bit cleaner and less dependent on the pausemenu
- fix issue where UI elements can be interacted with when the scene loader is transitioning scenes

fix minor UI bugs

---

Assets/Scenes/Levels/Chase.unity
Assets/Scenes/Levels/Mike Part 1.unity
Assets/Scenes/Levels/Nathan Part 3.unity
Assets/Timelines/Level Cutscenes/Claire Part 1/C1 1 Claire Meets Stickman.playable
Assets/Timelines/Level Cutscenes/Claire Part 1/C1 2 Claire Puzzle 1.playable
Assets/Timelines/Level Cutscenes/Claire Part 1/C1 3 Claire Puzzle 2.playable
Assets/Timelines/Level Cutscenes/Claire Part 1/C1 4 Claire Cliff.playable
Assets/Timelines/Level Cutscenes/Claire Part 2/C2 1.1 Claire Chair.playable
Assets/Timelines/Level Cutscenes/Claire Part 2/C2 2 Claire Sunset.playable
Assets/Timelines/Level Cutscenes/Claire Part 2/C2 3 Claire Puzzle 3.playable
Assets/Timelines/Level Cutscenes/Claire Part 2/C2 4 Claire Puzzle 4.playable
Assets/Timelines/Level Cutscenes/Claire Part 2/C2 5 Claire Cliff.playable
Assets/Timelines/Level Cutscenes/Claire Part 2/C2 6.1 Claire Death.playable
Assets/Timelines/Level Cutscenes/Claire Part 2/C2 6.2 Claire Death.playable
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 1 Mike Entrance.playable
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 2.1 Mike Needs Box.playable
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 2.2 Mike Tackle Scribble.playable
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 3.2 Mike Fall.playable
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 4.1 Mike Fight Scribble.playable
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 4.3 Mike Gets Up.playable
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 5 Mike Tired.playable
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 1 Mike Saves Stickman.playable
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 2.1 Stickman Falls Down Hole.playable
Assets/Timelines/Level Cutscenes/Nathan Part 1/N1 6 Empty Hall.playable
Assets/Timelines/Level Cutscenes/Nathan Part 3/N3 19 Confronting Nathan.playable

- add a keyframe in each applicable cutscene to ensure stickman is flipped the right way
- this will make sure stickman faces the right way regardless of which way they enter the cutscene trigger

ensure stickman sprite is flipped correctly in beginning of cutscenes

---

Assets/Configuration/Camera Noise Profile.asset
Assets/Configuration/Camera Noise Profile.asset.meta
Assets/Prefabs/Drawing Canvas/Drawing Canvas.prefab
Assets/Scenes/Levels/Chase.unity
Assets/Scenes/Levels/Mike Part 3.unity
Assets/Scenes/Levels/Nathan Part 1.unity
Assets/Scripts/Drawing Canvas/DrawingCanvas.cs
Assets/Timelines/Level Cutscenes/Mike Part 3/M3 7 Mike Death.playable
Assets/Timelines/Level Cutscenes/Nathan Part 1/N1 6 Empty Hall.playable

- add camera shake to mike part 3, chase level, and nathan cutscene 6

implement camera shake for intense scenes

---

Assets/Prefabs/Orange Object.prefab
Assets/Scenes/Levels/Chase.unity
Assets/Scenes/Levels/Mike Part 1.unity
Assets/Scenes/Levels/Mike Part 2.unity
Assets/Scripts/Respawnables/OrangeObject.cs
Assets/Scripts/Saving and Loading/GameManager.cs
Assets/Scripts/Saving and Loading/Serializable Data Objects/GameData.cs
Assets/Scripts/Saving and Loading/Serializable Data Objects/OrangeObjectData.cs
Assets/Scripts/Saving and Loading/Serializable Data Objects/OrangeObjectData.cs.meta

Orange objects will now save their position and body type (static/dynamic)
Generated IDs for Orange objects in levels that have them
Orange Object prefab has OrangeObjectData script added

Orange object saved state

---

Assets/Scenes/Levels/Mike Part 2.unity

Moved orange object respawn block in m p2

---

Assets/Prefabs/Ground Pieces/Mike Part 2 Ground.prefab
Assets/Scenes/Levels/Mike Part 2.unity
Assets/Scripts/PlayerMovement.cs

- many players are saying they want space to jump, so we'll give players what they want lol
- updated some misplaced bg art in mike part 2
- added an additional checkpoint to make players' lives easier

implement space to jump

---

Assets/Prefabs/Gameplay Systems/Respawn Manager.prefab
Assets/Prefabs/Gameplay Systems/Respawn Manager.prefab.meta
Assets/Scenes/Levels/Chase.unity
Assets/Scripts/Respawnables/RespawnManager.cs

Added respawning on death to "sandpit" orange blocks in chase level

Respawn Manager in Chase + Rename in Script

---

Assets/Dialogue/Nathan Part 2/8 Classroom.asset
Assets/Dialogue/Nathan Part 3/18 Bus Stop.asset
Assets/Dialogue/Nathan Part 3/19 Confronting Nathan.asset
Assets/Dialogue/Nathan Part 3/20 Nathan Hug.asset

After further playtesting, a few of the dialogue objects didn't portray Nathan's character and the end message of the game too well.  Revised accordingly

Revised some Dialogue Objects

---

Assets/Scenes/Levels/Mike Part 1.unity
Assets/Scenes/Levels/Mike Part 2.unity

Small adjustments to mike p1 and p2. Ignore the name of the 1st commit, i forgot to change it. stuff like focus area size, positions of objects, enemies, etc

Mike p2 touchups

---

ProjectSettings/ProjectSettings.asset

bump to 1.0

---

Assets/Scenes/IRL Cutscenes/The End.unity
Assets/Scenes/Levels/Chase.unity
Assets/Timelines/Level Cutscenes/Nathan Part 1/N1 6 Empty Hall.playable

- the end text not scaling to aspect ratio
- chase scribble wall respawn fix from before not actually saved
- crumple/paper sfx too ear-piercing

squeeze in more bug fixes before release

---

Assets/Scenes/Levels/Mike Part 2.unity

- readjust focus area size of bowling puzzle in mike part 2

fix focus area sizing for mike holds scribbles cutscene

---

Assets/Audio/Ambience/Park2 Ambience.wav.meta
Assets/Audio/Ambience/Police Siren.wav.meta
Assets/Audio/Ambience/Rumbling_mixdown.wav.meta
Assets/Scenes/Levels/Nathan Part 2.unity
Assets/Scenes/Levels/Nathan Part 3.unity

small ambience updates like increasing volume.

Increased volume and added cafeteria ambience

---

.vscode/settings.json
Assets/Dialogue/Claire Part 2/5.7 Chair.asset
Assets/Dialogue/Claire Part 2/5.7 Chair.asset.meta
Assets/Dialogue/Claire Part 2/5.8 Chair.asset
Assets/Dialogue/Claire Part 2/5.8 Chair.asset.meta
Assets/Dialogue/Mike Part 2/7.4 Stickman Falls.asset
Assets/Dialogue/Mike Part 2/7.4 Stickman Falls.asset.meta
Assets/Dialogue/Mike Part 2/8.2 Mike Meet Up Again.asset
Assets/Dialogue/Mike Part 2/8.2 Mike Meet Up Again.asset.meta
Assets/Dialogue/Mike Part 2/8.3 Mike Meet Up Again.asset
Assets/Dialogue/Mike Part 2/8.3 Mike Meet Up Again.asset.meta

Added the new dialogue Objects with avatars for the new optional Claire and Mike cutscenes we're adding for achievements

Added New Dialogue Options

---

Assets/Prefabs/Stickman.prefab
Assets/Scripts/PlayerMovement.cs

- add achievements for respawning 20 and 30 times at same checkpoint

add more respawn achievements

---

Assets/Scenes/Levels/Nathan Part 1.unity
Assets/Timelines/Level Cutscenes/Nathan Part 1/N1 6 Empty Hall.playable

- add a trigger for the avoidance achievement
- enable the trigger only after the paper crumple cutscene

add avoidance achievement

---

Assets/Dialogue/Mike Part 2/7.5 Stickman Fall.asset
Assets/Dialogue/Mike Part 2/7.5 Stickman Fall.asset.meta
Assets/Dialogue/Mike Part 2/7.6 Stickman Fall.asset
Assets/Dialogue/Mike Part 2/7.6 Stickman Fall.asset.meta

To smoothen out the transition for the alternate route Mike level cutscene in Part 2, additional dialogue objects have been added/revised.

Added additional dialogue objects

---

Assets/AddressableAssetsData/AssetGroups/Localization-Assets-English.asset
Assets/AddressableAssetsData/AssetGroups/Localization-Assets-Shared.asset
Assets/AddressableAssetsData/AssetGroups/Localization-String-Tables-English.asset
Assets/AddressableAssetsData/AssetGroups/Localization-String-Tables-中文（简体）.asset
Assets/Localization/Asset Tables/Dialogue Shared Data.asset
Assets/Localization/Asset Tables/Dialogue_en.asset
Assets/Localization/String Tables/Credits Shared Data.asset
Assets/Localization/String Tables/Credits Shared Data.asset.meta
Assets/Localization/String Tables/Credits.asset
Assets/Localization/String Tables/Credits.asset.meta
Assets/Localization/String Tables/Credits_en.asset
Assets/Localization/String Tables/Credits_en.asset.meta
Assets/Localization/String Tables/Credits_zh-CN.asset
Assets/Localization/String Tables/Credits_zh-CN.asset.meta
Assets/Prefabs/Credits/Credits Section.prefab
Assets/Prefabs/Credits/Credits.prefab
Assets/Scenes/IRL Cutscenes/Claire Cutoff.unity
Assets/Scenes/IRL Cutscenes/Claire Runs Into Nathan.unity
Assets/Scenes/IRL Cutscenes/Mike Cutoff.unity
Assets/Scenes/IRL Cutscenes/The End.unity

Localize credits

---

Assets/AddressableAssetsData/AssetGroups/Localization-Assets-English.asset
Assets/Dialogue/Mike Part 2/Mike 6.1 - Mike saves Stickman.asset
Assets/Dialogue/Mike Part 2/Mike 7.5 - Stickman Falls (Alt).asset
Assets/Dialogue/Mike Part 2/Mike 7.6 - Stickman Falls (Alt).asset
Assets/Dialogue/Nathan Part 3/Nathan 18 - Bus Stop.asset
Assets/Dialogue/Nathan Part 3/Nathan 19 - Confronting Nathan.asset
Assets/Dialogue/Nathan Part 3/Nathan 20 - Nathan Hug.asset
Assets/Dialogue/Nathan Part 3/Nathan 21 - Nathan Final.asset
Assets/Localization/Asset Tables/Dialogue Shared Data.asset
Assets/Localization/Asset Tables/Dialogue_en.asset
Assets/Prefabs/Credits/Credits Section.prefab
Assets/Prefabs/Credits/Credits.prefab
Assets/Scenes/IRL Cutscenes/Claire Cutoff.unity
Assets/Scenes/IRL Cutscenes/Claire Runs Into Nathan.unity
Assets/Scenes/IRL Cutscenes/Mike Cutoff.unity
Assets/Scenes/Levels/Claire Part 1.unity
Assets/Scenes/Levels/Claire Part 2.unity
Assets/Scenes/Levels/Mike Part 1.unity
Assets/Scenes/Levels/Mike Part 2.unity
Assets/Scenes/Levels/Mike Part 3.unity
Assets/Scenes/Levels/Nathan Part 1.unity
Assets/Scenes/Levels/Nathan Part 2.unity
Assets/Scenes/Levels/Nathan Part 3.unity

- add the localizer mappings to the dialogue system instances
- create the table rows for the dialogue asset table

add localizer mappings to dialogue system instances

---

Assets/Prefabs/Gameplay Systems/Dialogue System.prefab
Assets/Timelines/IRL Cutscenes/Claire Cutoff.playable
Assets/Timelines/IRL Cutscenes/Claire Runs Into Nathan.playable
Assets/Timelines/IRL Cutscenes/Drawing In Class.playable
Assets/Timelines/IRL Cutscenes/Mike Cutoff.playable
Assets/Timelines/Level Cutscenes/Claire Part 1/C1 1 Claire Meets Stickman.playable
Assets/Timelines/Level Cutscenes/Claire Part 1/C1 2 Claire Puzzle 1.playable
Assets/Timelines/Level Cutscenes/Claire Part 2/C2 1.1 Claire Chair.playable
Assets/Timelines/Level Cutscenes/Mike Part 1/M1 1 Mike Entrance.playable
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 1 Mike Saves Stickman.playable
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 2.1 Stickman Falls Down Hole.playable
Assets/Timelines/Level Cutscenes/Mike Part 3/M3 7 Mike Death.playable
Assets/Timelines/Level Cutscenes/Nathan Part 1/N1 1 Empty Hall.playable
Assets/Timelines/Level Cutscenes/Nathan Part 1/N1 2 Empty Hall.playable
Assets/Timelines/Level Cutscenes/Nathan Part 1/N1 3 Empty Hall.playable
Assets/Timelines/Level Cutscenes/Nathan Part 1/N1 4 Empty Hall.playable
Assets/Timelines/Level Cutscenes/Nathan Part 1/N1 5 Empty Hall.playable
Assets/Timelines/Level Cutscenes/Nathan Part 1/N1 7 Empty Hall.playable
Assets/Timelines/Level Cutscenes/Nathan Part 2/N2 8 Classroom.playable
Assets/Timelines/Level Cutscenes/Nathan Part 2/N2 9 Cool Art.playable
Assets/Timelines/Level Cutscenes/Nathan Part 3/N3 18 Bus Stop.playable
Assets/Timelines/Level Cutscenes/Nathan Part 3/N3 19 Confronting Nathan.playable

- fix borked dialogue signal bindings for dialogue1 and dialogue 2
i love unity

fix dialogue signal bindings

---

Assets/AddressableAssetsData/AssetGroups/Localization-Locales.asset
Assets/Prefabs/UI/Content Warning Dialog Variant.prefab
Assets/Prefabs/UI/Content Warning Dialog Variant.prefab.meta
Assets/Prefabs/UI/Content Warning.prefab
Assets/Prefabs/UI/Main Menu.prefab

- add the language button and menu to the content warning dialog
- hide all language buttons for the upcoming release
- remove the Spanish locale

disable language menu UI

---

Assets/Scenes/Levels/Mike Part 2.unity
Assets/Scripts/PlayerMovement.cs
Assets/Scripts/Respawnables/OrangeObject.cs
Assets/Timelines/Level Cutscenes/Claire Part 2/C2 5 Claire Cliff.playable
Assets/Timelines/Level Cutscenes/Mike Part 2/M2 2.3 Stickman Falls Down Hole (Alt).playable

- refine cutscene animations
- claire part 2 cliff
- mike part 2 stickman falls down alt
- add logic to trigger orange obj when player jumps from it, even if the player does not actually touch the orange object

refine player movement and cutscenes

---

Assets/Prefabs/Stickman.prefab
Assets/Scenes/Levels/Tutorial.unity
Assets/Scripts/Saving and Loading/Serializable Data Objects/CheckpointData.cs
Assets/Scripts/Saving and Loading/Serializable Data Objects/CutsceneData.cs
Assets/Scripts/Saving and Loading/Serializable Data Objects/OrangeObjectData.cs

i cant believe we're catching these now

fix more guid conflicts and missing guids
